In [37]:
# Consider the below code to answer further questions:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [38]:
print("Data type of variables list_ :",type(list_))

Data type of variables list_ : <class 'list'>


In [39]:
print("Data type of variables array_list :",(array_list.dtype))

Data type of variables array_list : <U1


#### Difference in the data type of variables list_ and array_list

#### class 'list'
* A list can be defined as a collection of values or items of different types.
* This the a normal list that we use in python
* It's data types is <class 'list'>


#### class 'numpy.ndarray'
* Ndarray is the n-dimensional array object defined in the numpy which stores the collection of the similar type of elements. In other words, we can define a ndarray as the collection of the data type (dtype) objects.
* This is an numpy array
* It's data types is <class 'numpy.ndarray'>


#### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [40]:
#data type of each and every element of the variables list_
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [41]:
#data type of each and every element of the variables array_list
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#### Difference in the data type of variables list_ and array_list

#### class 'list'
A list can be defined as a collection of values or items of different types.

#### class 'numpy.ndarray'
Ndarray is the n-dimensional array object defined in the numpy which stores the collection of the similar type of elements. In other words, we can define a ndarray as the collection of the data type (dtype) objects.

#### Q3. Considering the following changes in the variable, array_list:

**array_list = np.array(object = list_, dtype = int)**

**Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.**


In [42]:
array_list2 = np.array(object = list_, dtype = int)
array_list2

array([1, 2, 3, 4, 5])

In [43]:
#data type of each and every element of the variables list_
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [44]:
#data type of each and every element of the variables array_list2
for i in array_list2:
    print(type(i))
      
# This types has been changes form Str(Unicode string) to Integer

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [19]:
# Consider the below code to answer further questions:**

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

#### Q4. Write a code to find the following characteristics of variable, num_array:

In [45]:
#(i) shape
print("Shape of the array: ",num_array.shape)

# (ii) size
print("Size of the array: ",num_array.size)

Shape of the array:  (2, 3)
Size of the array:  6


#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [29]:
arr=np.zeros((3, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [35]:
id_mat=np.eye(5)
print(id_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
